import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { createChatbot } from '../packages/core/dist/index.js';
import { SqliteStore } from '../packages/core/dist/storage.js';
import { buildMessages } from '../packages/core/dist/context.js';
const originalFetch=globalThis.fetch;
const streamReply=()=>new Response('data: {"choices":[{"delta":{"content":"Answer"}}]}\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});
async function fixture(extra={},provider=()=>streamReply()) {
 const dir=await mkdtemp(`${tmpdir()}/chat-review-`),filename=`${dir}/db.sqlite`;
 globalThis.fetch=async(_,init)=>provider(JSON.parse(init.body),init);
 const bot=createChatbot({provider:{baseUrl:'https://mock.test/v1/',apiKey:'test',model:'test',compatibility:'openrouter'},identity:()=>({userId:'u'}),storage:{filename},...extra});await bot.ready;
 const call=(path,body)=>bot.handle(new Request(`http://app.test${path}`,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{}));
 const id=(await(await call('/conversations',{})).json()).conversation.id;
 return {bot,call,id,filename,async close(){await bot.close();globalThis.fetch=originalFetch;await rm(dir,{recursive:true,force:true});}};
}
test('web search is sent without host tools',async()=>{let payload;const f=await fixture({capabilities:{webSearch:{enabled:true}}},p=>{payload=p;return streamReply();});try{await(await f.call(`/conversations/${f.id}/messages`,{content:'Search'})).text();assert.equal(payload.tools?.[0]?.type,'openrouter:web_search');}finally{await f.close();}});
test('suggestions survive history and cancellation preserves completed answer',async()=>{let entered,release;const ready=new Promise(r=>entered=r),gate=new Promise(r=>release=r);const f=await fixture({capabilities:{suggestions:{enabled:true}}},async(p,init)=>{if(p.stream)return streamReply();entered();await Promise.race([gate,new Promise((_,reject)=>init.signal.addEventListener('abort',()=>reject(Error('abort')),{once:true}))]);return Response.json({choices:[{message:{content:'{"suggestions":["Next step?"]}'}}]});});try{const response=await f.call(`/conversations/${f.id}/messages`,{content:'Help'});const reader=response.body.getReader();await ready;await reader.cancel();release();await f.bot.close();const store=new SqliteStore(f.filename);assert.equal(store.messages(f.id).at(-1).status,'complete');store.close();}finally{await f.close();}});
test('suggestions are persisted on assistant messages',async()=>{const f=await fixture({capabilities:{suggestions:{enabled:true}}},p=>p.stream?streamReply():Response.json({choices:[{message:{content:'{"suggestions":["Next step?"]}'}}]}));try{await(await f.call(`/conversations/${f.id}/messages`,{content:'Help'})).text();const history=await(await f.call(`/conversations/${f.id}`)).json();assert.deepEqual(history.messages.at(-1).suggestions,['Next step?']);}finally{await f.close();}});
test('summary survives a populated profile and personalization disabled',async()=>{const f=await fixture();const store=new SqliteStore(f.filename);try{store.user('default','u',{bio:'x'.repeat(1100),other:'y'.repeat(1100)});store.updateSummary(f.id,'The agreed launch date is Friday.',0);for(const personalizationTokens of [0,800]){const result=await buildMessages(store,'default','u',f.id,'When is launch?','',{personalizationTokens});assert.ok(result.messages.some(m=>m.content.includes('launch date is Friday')));assert.ok(result.estimate<=6000);}}finally{store.close();await f.close();}});
test('maintenance does not lock completed replies and cursor covers only summarized messages',async()=>{let entered,release,prompt,maintained;const saved=new Promise(r=>maintained=r);const ready=new Promise(r=>entered=r),gate=new Promise(r=>release=r);const f=await fixture({context:{summaryAfterMessages:4,recentMessages:4},onEvent:event=>{if(event.type==='usage'&&event.data?.kind==='summary')maintained();}},async p=>{if(p.stream)return streamReply();prompt=p.messages.at(-1).content;entered();await gate;return Response.json({choices:[{message:{content:'Summary'}}]});});const store=new SqliteStore(f.filename);try{for(let i=0;i<110;i++)store.addMessage(f.id,i%2?'assistant':'user',`message-${i} ${'x'.repeat(400)}`);const first=await f.call(`/conversations/${f.id}/messages`,{content:'First'});await first.text();await ready;const second=await f.call(`/conversations/${f.id}/messages`,{content:'Second'});release();await second.text();assert.equal(second.status,200);await saved;await f.bot.close();const summary=store.summary(f.id);const included=[...prompt.matchAll(/message-\d+/g)];assert.ok(prompt.includes('message-0'));assert.equal(summary.messageCount,included.length);assert.ok(prompt.length<=30000);}finally{release();store.close();await f.close();}});
test('Express normal response close does not cancel maintenance',async()=>{const {default:express}=await import('express');const {expressHandler}=await import('../packages/core/dist/express.js');let maintained;const finished=new Promise(r=>maintained=r);const f=await fixture({context:{summaryAfterMessages:4,recentMessages:4},onEvent:e=>{if(e.type==='usage'&&e.data?.kind==='summary')maintained();}},async p=>{if(p.stream)return streamReply();await new Promise(r=>setTimeout(r,20));return Response.json({choices:[{message:{content:'Summary'}}]});});const store=new SqliteStore(f.filename);for(let i=0;i<6;i++)store.addMessage(f.id,i%2?'assistant':'user',`message ${i}`);store.close();const app=express();app.use(expressHandler(f.bot));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));let timer;try{const response=await originalFetch(`http://127.0.0.1:${server.address().port}/conversations/${f.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:'Help'})});await response.text();await Promise.race([finished,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('maintenance canceled after normal response close')),200))]);}finally{clearTimeout(timer);await new Promise(r=>server.close(r));await f.close();}});
test('oversized historical message is summarized in bounded chunks without skipping its tail',async()=>{let maintained;const finished=new Promise(r=>maintained=r),prompts=[];const f=await fixture({context:{summaryAfterMessages:4,recentMessages:4},onEvent:e=>{if(e.type==='usage'&&e.data?.kind==='summary')maintained();}},p=>{if(p.stream)return streamReply();prompts.push(p.messages.at(-1).content);return Response.json({choices:[{message:{content:'Summary'}}]});});const store=new SqliteStore(f.filename);let timer;try{store.addMessage(f.id,'user','START '+ 'x'.repeat(40000)+' TAIL');for(let i=0;i<5;i++)store.addMessage(f.id,'assistant','Reply');await(await f.call(`/conversations/${f.id}/messages`,{content:'Continue'})).text();await Promise.race([finished,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('oversized message blocked summary cursor')),100))]);assert.ok(prompts.length>=2);assert.ok(prompts[0].includes('START'));assert.ok(prompts.at(-1).includes('TAIL'));assert.ok(prompts.every(p=>p.length<=30000));assert.equal(store.summary(f.id).messageCount,1);}finally{clearTimeout(timer);store.close();await f.close();}});
test('SQLite v5 migration preserves messages and adds persisted suggestions',async()=>{const {default:Database}=await import('better-sqlite3');const dir=await mkdtemp(`${tmpdir()}/chat-migration-`),filename=`${dir}/db.sqlite`;let store=new SqliteStore(filename);const id=store.create('default','u').id,msg=store.addMessage(id,'assistant','Existing answer');store.close();const db=new Database(filename);db.exec('ALTER TABLE messages DROP COLUMN suggestions; PRAGMA user_version = 5;');db.close();try{store=new SqliteStore(filename);assert.equal(store.messages(id)[0].content,'Existing answer');assert.deepEqual(store.messages(id)[0].suggestions,[]);store.setSuggestions(msg,['Continue']);store.close();store=new SqliteStore(filename);assert.deepEqual(store.messages(id)[0].suggestions,['Continue']);}finally{store.close();await rm(dir,{recursive:true,force:true});}});
