import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
import {mount} from '../packages/widget/dist/index.js';
import {OmniChatbot} from '../packages/react/src/index.js';
const dom=new JSDOM('<html><body></body></html>',{url:'http://lan.test/'});
for(const name of ['window','document','location','HTMLElement'])globalThis[name]=dom.window[name];
Object.defineProperty(dom.window.HTMLElement.prototype,'part',{get(){return {add(){}};}});
globalThis.matchMedia=()=>({matches:false});globalThis.CSS={supports:()=>true};globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const config={branding:{name:'Mira',greeting:'Hello',theme:'light',placement:'bottom-right',width:380,height:650},capabilities:{suggestions:true}};
let posted=0,streamController;
function setup({pending=false}={}){document.body.replaceChildren();posted=0;globalThis.fetch=async(input,init={})=>{const url=String(input);if(url.endsWith('/config'))return Response.json(config);if(url.endsWith('/conversations'))return Response.json({conversation:{id:'chat'},conversations:[{id:'chat',title:'Chat'}]});if(url.endsWith('/messages')){posted++;return new Response(new ReadableStream({start(c){streamController=c;if(!pending){c.enqueue(new TextEncoder().encode('event: delta\ndata: {"text":"Answer"}\n\nevent: suggestions\ndata: {"prompts":["Next step?"]}\n\nevent: done\ndata: {}\n\n'));c.close();}}}));}return Response.json({messages:[{id:'a',role:'assistant',content:'Answer',status:'complete',suggestions:['Next step?']}]});};const host=document.createElement('div');document.body.append(host);return host;}
const tick=()=>new Promise(r=>setTimeout(r,0));
function send(host,text='Help'){const root=host.shadowRoot;root.querySelector('textarea').value=text;root.querySelector('form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));}
test('LAN send works without randomUUID',async()=>{const crypto=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{configurable:true,value:{getRandomValues:crypto.getRandomValues.bind(crypto)}});const host=setup();const widget=mount(host,{endpoint:'/api'});try{await widget.ready;send(host);await tick();assert.equal(posted,1);assert.equal(host.shadowRoot.querySelector('.status').textContent,'Assistant response complete.');}finally{widget.destroy();Object.defineProperty(globalThis,'crypto',{configurable:true,value:crypto});}});
test('updates preserve draft and stream elements',async()=>{const host=setup({pending:true});const widget=mount(host,{endpoint:'/api'});try{await widget.ready;const area=host.shadowRoot.querySelector('textarea');area.value='Draft';widget.update({name:'New name'});assert.equal(host.shadowRoot.querySelector('textarea').value,'Draft');send(host);await tick();widget.update({theme:'dark'});streamController.enqueue(new TextEncoder().encode('event: delta\ndata: {"text":"Visible reply"}\n\nevent: done\ndata: {}\n\n'));streamController.close();await tick();assert.match(host.shadowRoot.querySelector('.messages').textContent,/Visible reply/);}finally{widget.destroy();}});
test('React parent renders preserve drafts',async()=>{const target=setup();const root=createRoot(target);try{await act(async()=>root.render(React.createElement(OmniChatbot,{endpoint:'/api',name:'Mira'})));const host=target.firstElementChild;host.shadowRoot.querySelector('textarea').value='Keep this draft';await act(async()=>root.render(React.createElement(OmniChatbot,{endpoint:'/api',name:'Mira'})));assert.equal(host.shadowRoot.querySelector('textarea').value,'Keep this draft');}finally{await act(async()=>root.unmount());}});
test('history restores suggestion buttons',async()=>{const host=setup();const widget=mount(host,{endpoint:'/api'});try{await widget.ready;send(host);await tick();host.shadowRoot.querySelector('.toolbar button').click();await tick();host.shadowRoot.querySelector('.action').click();await tick();const pill=host.shadowRoot.querySelector('.followups button');assert.equal(pill?.textContent,'Next step?');pill.click();assert.equal(host.shadowRoot.querySelector('textarea').value,'Next step?');}finally{widget.destroy();}});
