import { Pool, type PoolClient } from "pg";
import type { Store } from "./interface.js";

const iso=(value:Date|string)=>value instanceof Date?value.toISOString():new Date(value).toISOString();
const migration=`
CREATE TABLE IF NOT EXISTS chatbot_users(instance_id text NOT NULL,user_id text NOT NULL,profile jsonb NOT NULL DEFAULT '{}'::jsonb,preferences jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL,PRIMARY KEY(instance_id,user_id));
CREATE TABLE IF NOT EXISTS chatbot_conversations(id text PRIMARY KEY,instance_id text NOT NULL,user_id text NOT NULL,title text NOT NULL DEFAULT 'New conversation',summary text,summary_message_count integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS chatbot_conversations_owner ON chatbot_conversations(instance_id,user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS chatbot_messages(id text PRIMARY KEY,conversation_id text NOT NULL REFERENCES chatbot_conversations(id) ON DELETE CASCADE,role text NOT NULL,content text NOT NULL,status text NOT NULL DEFAULT 'complete',request_id text,media_ids jsonb NOT NULL DEFAULT '[]'::jsonb,usage_input integer,usage_output integer,created_at timestamptz NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS chatbot_messages_request ON chatbot_messages(conversation_id,request_id) WHERE request_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS chatbot_memories(id text PRIMARY KEY,instance_id text NOT NULL,user_id text NOT NULL,source_conversation text,content text NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS chatbot_memories_owner ON chatbot_memories(instance_id,user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS chatbot_usage(id text PRIMARY KEY,instance_id text NOT NULL,user_id text NOT NULL,conversation_id text,input_estimate integer NOT NULL DEFAULT 0,input_actual integer,output_actual integer,kind text NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS chatbot_media(id text PRIMARY KEY,instance_id text NOT NULL,user_id text NOT NULL,conversation_id text,mime text NOT NULL,bytes bytea NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS chatbot_conversation_locks(lock_key text PRIMARY KEY,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS chatbot_rate_limits(instance_id text NOT NULL,user_id text NOT NULL,window_start timestamptz NOT NULL,request_count integer NOT NULL,PRIMARY KEY(instance_id,user_id));
`;

export class PostgresStore implements Store {
  private constructor(private pool:Pool){}
  static async open(connectionString:string){
    const store=new PostgresStore(new Pool({connectionString,application_name:"metanoia-chatbot"}));
    let client:PoolClient|undefined;
    try{
      client=await store.pool.connect();
      await client.query("BEGIN");
      await client.query("CREATE TABLE IF NOT EXISTS chatbot_schema_migrations(version integer PRIMARY KEY,applied_at timestamptz NOT NULL)");
      const current=await client.query<{version:number}>("SELECT COALESCE(MAX(version),0) AS version FROM chatbot_schema_migrations");
      const version=Number(current.rows[0]?.version??0);if(version>7)throw new Error(`Chatbot database schema ${version} is newer than this package supports.`);
      if(version===0){await client.query(migration);await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(1,now())");}
      if(version<2){await client.query("CREATE TABLE IF NOT EXISTS chatbot_conversation_locks(lock_key text PRIMARY KEY,expires_at timestamptz NOT NULL)");await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(2,now()) ON CONFLICT(version) DO NOTHING");}
      if(version<3){await client.query("ALTER TABLE chatbot_conversations ADD COLUMN IF NOT EXISTS summary_message_count integer NOT NULL DEFAULT 0");await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(3,now()) ON CONFLICT(version) DO NOTHING");}
      if(version<4){await client.query("CREATE TABLE IF NOT EXISTS chatbot_rate_limits(instance_id text NOT NULL,user_id text NOT NULL,window_start timestamptz NOT NULL,request_count integer NOT NULL,PRIMARY KEY(instance_id,user_id))");await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(4,now()) ON CONFLICT(version) DO NOTHING");}
      if(version<5){await client.query("ALTER TABLE chatbot_usage ADD COLUMN IF NOT EXISTS cached_input integer");await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(5,now()) ON CONFLICT(version) DO NOTHING");}
      if(version<6){await client.query("ALTER TABLE chatbot_messages ADD COLUMN IF NOT EXISTS suggestions jsonb NOT NULL DEFAULT '[]'::jsonb");await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(6,now()) ON CONFLICT(version) DO NOTHING");}
      if(version<7){await client.query("ALTER TABLE chatbot_messages ADD COLUMN IF NOT EXISTS media_ids jsonb NOT NULL DEFAULT '[]'::jsonb");await client.query("INSERT INTO chatbot_schema_migrations(version,applied_at) VALUES(7,now()) ON CONFLICT(version) DO NOTHING");}
      await client.query("COMMIT");
    }catch(error){if(client)try{await client.query("ROLLBACK");}catch{/* preserve the initialization error */}await store.pool.end();throw error;}finally{client?.release();}
    return store;
  }
  async user(instance:string,user:string,profile?:Record<string,unknown>){
    if(profile)await this.pool.query("INSERT INTO chatbot_users(instance_id,user_id,profile,created_at) VALUES($1,$2,$3::jsonb,now()) ON CONFLICT(instance_id,user_id) DO UPDATE SET profile=EXCLUDED.profile",[instance,user,JSON.stringify(profile)]);
    else await this.pool.query("INSERT INTO chatbot_users(instance_id,user_id,created_at) VALUES($1,$2,now()) ON CONFLICT(instance_id,user_id) DO NOTHING",[instance,user]);
    const result=await this.pool.query<{profile:Record<string,unknown>;preferences:Record<string,unknown>}>("SELECT profile,preferences FROM chatbot_users WHERE instance_id=$1 AND user_id=$2",[instance,user]);
    return {...result.rows[0]!.profile,...result.rows[0]!.preferences};
  }
  async list(instance:string,user:string){const r=await this.pool.query("SELECT id,title,created_at,updated_at FROM chatbot_conversations WHERE instance_id=$1 AND user_id=$2 ORDER BY updated_at DESC LIMIT 100",[instance,user]);return r.rows.map(x=>({...x,created_at:iso(x.created_at),updated_at:iso(x.updated_at)}));}
  async create(instance:string,user:string,title="New conversation"){const id=crypto.randomUUID(),at=new Date();const r=await this.pool.query("INSERT INTO chatbot_conversations(id,instance_id,user_id,title,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5) RETURNING id,title,created_at,updated_at",[id,instance,user,title,at]);return {...r.rows[0]!,created_at:iso(r.rows[0]!.created_at),updated_at:iso(r.rows[0]!.updated_at)};}
  async conversation(instance:string,user:string,id:string){const r=await this.pool.query("SELECT * FROM chatbot_conversations WHERE instance_id=$1 AND user_id=$2 AND id=$3",[instance,user,id]);const row=r.rows[0];return row?{...row,created_at:iso(row.created_at),updated_at:iso(row.updated_at)}:null;}
  async summary(id:string){const r=await this.pool.query<{summary:string|null;summary_message_count:number}>("SELECT summary,summary_message_count FROM chatbot_conversations WHERE id=$1",[id]);return {content:r.rows[0]?.summary??null,messageCount:Number(r.rows[0]?.summary_message_count??0)};}
  async updateSummary(id:string,content:string,messageCount:number){await this.pool.query("UPDATE chatbot_conversations SET summary=$1,summary_message_count=$2 WHERE id=$3",[content,messageCount,id]);}
  async messages(id:string){const r=await this.pool.query("SELECT id,role,content,status,created_at,suggestions,media_ids FROM chatbot_messages WHERE conversation_id=$1 ORDER BY created_at ASC",[id]);return r.rows.map(({media_ids,...x})=>({...x,created_at:iso(x.created_at),mediaIds:media_ids}));}
  async setSuggestions(id:string,prompts:string[]){await this.pool.query("UPDATE chatbot_messages SET suggestions=$1::jsonb WHERE id=$2",[JSON.stringify(prompts),id]);}
  async addMessage(id:string,role:string,content:string,status="complete",requestId?:string,mediaIds:string[]=[]){const msg=crypto.randomUUID(),client=await this.pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO chatbot_messages(id,conversation_id,role,content,status,request_id,media_ids,created_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,now())",[msg,id,role,content,status,requestId??null,JSON.stringify(mediaIds)]);await client.query("UPDATE chatbot_conversations SET updated_at=now() WHERE id=$1",[id]);await client.query("COMMIT");return msg;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async hasRequest(id:string,requestId:string){const r=await this.pool.query("SELECT 1 FROM chatbot_messages WHERE conversation_id=$1 AND request_id=$2",[id,requestId]);return r.rowCount!==0;}
  async completeMessage(id:string,content:string,status:string,input?:number,output?:number){await this.pool.query("UPDATE chatbot_messages SET content=$1,status=$2,usage_input=$3,usage_output=$4 WHERE id=$5",[content,status,input??null,output??null,id]);}
  async deleteConversation(instance:string,user:string,id:string){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("DELETE FROM chatbot_memories WHERE instance_id=$1 AND user_id=$2 AND source_conversation=$3",[instance,user,id]);await client.query("DELETE FROM chatbot_media WHERE instance_id=$1 AND user_id=$2 AND conversation_id=$3",[instance,user,id]);const result=await client.query("DELETE FROM chatbot_conversations WHERE instance_id=$1 AND user_id=$2 AND id=$3",[instance,user,id]);await client.query("COMMIT");return result.rowCount!==0;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async prefs(instance:string,user:string){const r=await this.pool.query<{preferences:Record<string,unknown>}>("SELECT preferences FROM chatbot_users WHERE instance_id=$1 AND user_id=$2",[instance,user]);return r.rows[0]?.preferences??{};}
  async updatePrefs(instance:string,user:string,value:Record<string,unknown>){await this.pool.query("UPDATE chatbot_users SET preferences=$1::jsonb WHERE instance_id=$2 AND user_id=$3",[JSON.stringify(value),instance,user]);}
  async memories(instance:string,user:string){const r=await this.pool.query("SELECT id,content,created_at FROM chatbot_memories WHERE instance_id=$1 AND user_id=$2 ORDER BY created_at DESC",[instance,user]);return r.rows.map(x=>({...x,created_at:iso(x.created_at)}));}
  async addMemory(instance:string,user:string,content:string,sourceConversation?:string){const id=crypto.randomUUID();await this.pool.query("INSERT INTO chatbot_memories(id,instance_id,user_id,source_conversation,content,created_at) VALUES($1,$2,$3,$4,$5,now())",[id,instance,user,sourceConversation??null,content]);return id;}
  async setMemory(instance:string,user:string,id:string,content:string){await this.pool.query("UPDATE chatbot_memories SET content=$1 WHERE instance_id=$2 AND user_id=$3 AND id=$4",[content,instance,user,id]);}
  async deleteMemory(instance:string,user:string,id:string){const r=await this.pool.query("DELETE FROM chatbot_memories WHERE instance_id=$1 AND user_id=$2 AND id=$3",[instance,user,id]);return r.rowCount!==0;}
  async addUsage(instance:string,user:string,conversation:string,inputEstimate:number,inputActual:number|undefined,outputActual:number|undefined,kind="chat",cachedInput?:number){await this.pool.query("INSERT INTO chatbot_usage(id,instance_id,user_id,conversation_id,input_estimate,input_actual,output_actual,cached_input,kind,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now())",[crypto.randomUUID(),instance,user,conversation,inputEstimate,inputActual??null,outputActual??null,cachedInput??null,kind]);}
  async userData(instance:string,user:string){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("DELETE FROM chatbot_media WHERE instance_id=$1 AND user_id=$2",[instance,user]);await client.query("DELETE FROM chatbot_usage WHERE instance_id=$1 AND user_id=$2",[instance,user]);await client.query("DELETE FROM chatbot_memories WHERE instance_id=$1 AND user_id=$2",[instance,user]);await client.query("DELETE FROM chatbot_conversations WHERE instance_id=$1 AND user_id=$2",[instance,user]);await client.query("DELETE FROM chatbot_rate_limits WHERE instance_id=$1 AND user_id=$2",[instance,user]);await client.query("DELETE FROM chatbot_users WHERE instance_id=$1 AND user_id=$2",[instance,user]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async putMedia(instance:string,user:string,conversation:string|undefined,mime:string,bytes:Buffer){const id=crypto.randomUUID();await this.pool.query("INSERT INTO chatbot_media(id,instance_id,user_id,conversation_id,mime,bytes,created_at) VALUES($1,$2,$3,$4,$5,$6,now())",[id,instance,user,conversation??null,mime,bytes]);return id;}
  async getMedia(instance:string,user:string,id:string){const r=await this.pool.query<{mime:string;bytes:Buffer}>("SELECT mime,bytes FROM chatbot_media WHERE instance_id=$1 AND user_id=$2 AND id=$3",[instance,user,id]);return r.rows[0];}
  async mediaForMessage(instance:string,user:string,id:string,conversation:string){const r=await this.pool.query<{mime:string;bytes:Buffer}>("SELECT mime,bytes FROM chatbot_media WHERE instance_id=$1 AND user_id=$2 AND id=$3 AND conversation_id=$4",[instance,user,id,conversation]);return r.rows[0];}
  async tryLock(key:string){const result=await this.pool.query<{lock_key:string}>("INSERT INTO chatbot_conversation_locks(lock_key,expires_at) VALUES($1,now()+interval '15 minutes') ON CONFLICT(lock_key) DO UPDATE SET expires_at=EXCLUDED.expires_at WHERE chatbot_conversation_locks.expires_at<now() RETURNING lock_key",[key]);if(!result.rowCount)return null;let done=false;const heartbeat=setInterval(()=>{void this.pool.query("UPDATE chatbot_conversation_locks SET expires_at=now()+interval '15 minutes' WHERE lock_key=$1",[key]).catch(()=>undefined);},60_000);heartbeat.unref();return async()=>{if(done)return;done=true;clearInterval(heartbeat);await this.pool.query("DELETE FROM chatbot_conversation_locks WHERE lock_key=$1",[key]);};}
  async hitRateLimit(instance:string,user:string,limit:number,windowMs:number){const result=await this.pool.query<{request_count:number}>("INSERT INTO chatbot_rate_limits(instance_id,user_id,window_start,request_count) VALUES($1,$2,now(),1) ON CONFLICT(instance_id,user_id) DO UPDATE SET window_start=CASE WHEN chatbot_rate_limits.window_start+($3::double precision*interval '1 millisecond')<=now() THEN now() ELSE chatbot_rate_limits.window_start END,request_count=CASE WHEN chatbot_rate_limits.window_start+($3::double precision*interval '1 millisecond')<=now() THEN 1 ELSE chatbot_rate_limits.request_count+1 END RETURNING request_count",[instance,user,windowMs]);return Number(result.rows[0]?.request_count??0)<=limit;}
  async close(){await this.pool.end();}
}
